---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: sealed-secrets
  namespace: flux
  labels:
    chart: sealed-secrets
spec:
  chartGitPath: sealed-secrets
  releaseName: sealed-secrets
  values:
    image:
      repository: quay.io/bitnami/sealed-secrets-controller
      tag: v0.7.0
