apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openfaas-token
  namespace: openfaas-fn
  annotations:
    flux.weave.works/ignore: "false"
spec:
  encryptedData:
    token: AgAQDO58WniIV3gTkuMSsJsx1gxXbEVhWu0Oq+DmwC1cT5QtEzEWwd3NFvCKqR6XdDkIy5HRlt1P9MOQhNwkQX1A+IWd7/YgVTo8Mmv1OeNntZoIMiLRxm4bY21vkLF1TngogzD0E4UQ4ezVpGikLpM3H7QhGaH7/huzeUqJE/PM4z/h5mwkzyirBKsOOvZlA8AvsfrheIXA8rcHcVZX3COsKJaPIKobUfHtU+NCbT3fxhzr+d6dqbtGCzex3253szhSbAqlWMMmVnV9MhryNLI+CQF3TzrTSPxIQXIDF1dSbrSvNn/tAxAobTjskRbYQ9eV95tM2Q3EcGC+DpKAv8ffKTzeEZ9+/neSbYhGohwEumrey/McgcyjlpRAxgSEp/6v11pdt9RW8lnnaYmJ5Ib4CfOl3U8mOdsLgZR81xT0relXVt7oHMeNyrlpGX/05zfiKV63pDAdgyqYJkIVLsGU3HqShG3yTyUrw40WqOL/hflUct8QQzu8CFkKMLIkkRFafCswJwtaGaaJ0PN0O6kYa3irHKC+MhCP3B9Gezy6rH7+KdhjyR0k4ZQXrsfOlRNyureRA1RMplVnozAgqf6xs99Q4xogs3Pa1JZU2ygGylonht+6+q5e7/qJ+lCTMejTmYxFYA4O24cGLNOMs13HLlEKczrSr5DEIlXuu7nfqSS9ppsVEbVOwqQaNhtcpvGeuiM5wA==
